### ISSUE TITLE
sistemare login

### ISSUE THREAD

**Issue by lucavivan** [lucavivan/manfe_vivan#4]
login non funziona correttamente, sarebbe meglio semplificare

**Comment by Simone-M-1966** [comment]
ok, gli do un'occhiata, facciamo il punto della situazione questa sera, tra
le 19:00 e le 20:30 sono libero, oppure dopo le 21:30.

Il giorno lun 18 mag 2020 alle ore 05:44 lucavivan <notifications@github.com>
ha scritto:

**Comment by Simone-M-1966** [comment]
Dopo alcuni tentativi il problema del login, all'nterno della classe Gui, sembra risalire a un contrasto con la classe [Scanner](https://teamtreehouse.com/community/javautilnosuchelementexception-no-line-found-look-around-scannerjava-line-1540) interna all jdk di java, soluzione attuale non chiara.
Necessaria revisione del secondo input da tastiera nel login, legato all'iserimento della password.

**Comment by Simone-M-1966** [comment]
Possibile soluzione per il [problema](https://stackoverflow.com/questions/7209110/java-util-nosuchelementexception-no-line-found) legato al login, interno alla classe Gui.

**Comment by lucavivan** [comment]
risolto in commit add0db8b87f88e67ce16cd363c623a54177d7c6d
